version: "2.1"

services:

  node:
    image: approov/node-express-shapes-demo
    build: ./docker
    restart: always
    env_file: .env.example
    environment:
      - HTTP_PROTOCOL=https
      - DEBUG=approov-protected-server
    networks:
      - traefik
      - default
    command: "npm start"
    volumes:
      - ./:/home/node/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.backend=approov-node-express-shapes-demo"
      - "traefik.docker.network=traefik"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:node-express-shapes-demo.pdm.approov.io"

networks:
  traefik:
    external: true
