version: "2.1"

services:

  server:
    image: ${IMAGE_NAME:-approov/node}
    build:
      context: docker/build
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${NODE_DIR:-./}:/home/node/workspace
      - ./postman/collections:/home/node/postman/collections
    working_dir: /home/node/workspace/server
    command:
      - postman
    networks:
      - node_demo_network

networks:
  node_demo_network:
    driver: "bridge"
